name: Actions Workflow


on: [push]


jobs:
  run-github-actions:
    runs-on: self-hosted
    steps:
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Leandro Nunes do Nascimento'
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"

